### ISSUE TITLE
User Story #3: Computer Fire-Back Functionality

### ISSUE THREAD

**Issue by alfayeza** [OSU-CS361-W17/group4_project1#21]
**S**pecific Task: implementation of the Attack-back functionality for the computer. This task should allow the computer to attack-back by using random generator to choose specific place (x,y) on the user's grid.

**M**easuring: We can measure this task by attacking, then we should see the computer attacking-back, if the place generated (x,y) is available it will place a peg on the user's grid.
**A**chievability: This task is hard achievable since it is an essential task and require no action on the user side.
**R**elevance: yes, this functionality is a must to have a working battleship game.
**T**ime: this task will take approximately 2-5 hours

**Comment by yangx3** [comment]
computer fire-back can be easy solved with Attack function. After player attack, call computer fire back function. Random two integers for 1 point. It should check the computerHits and computerMisses list, make sure computer doesn't  attack the same point.
