### ISSUE TITLE
User Story #5: "Another Game" Button

### ISSUE THREAD

**Issue by alfayeza** [OSU-CS361-W17/group4_project1#26]
**S**pecific Task: implementation of a button that re-run the game, so that the user can play again without closing and re-running the game.

**M**easuring: We can measure this task easily by testing the button to see whether it works or not.
**A**chievability: This task is not essential, but achievable.
**R**elevance: yes, this task will add a nice functionality to the User Interface
**T**ime: this task will take approximately 1 hour

**Comment by 932543420** [comment]
Test didnt pass.

**Comment by 932543420** [comment]
Still not work
